runtime: python311
service: language-app

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

env_variables:
  BUCKET_NAME: ""
  DB_HOST: ""
  DB_USER: ""
  DB_PASS: ""
  DB_NAME: ""
  DB_PORT: "3306"
  TABLE_NAME: ""
  CONNECTION_NAME: ""